FACE/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Maria_Membership.urls')),
    # path('membership/', include('membership.urls')),
]

Maria_Membership/urls.py
from django.urls import path
from . import views

app_name = 'Maria_membership'

urlpatterns = [
    path('', views.home, name='home'),
    path('information/', views.information, name='information'),
    path('reqfacePicture/', views.reqfacePicture, name='reqfacePicture'),
    path('reqfaceRecog/', views.reqfaceRecog, name='reqfaceRecog'),
    path('menu/', views.menu, name='menu'),
    path('stamp/', views.stamp, name='stamp'),
    path('mypage/',views.mypage, name='mypage'),
    path('order_complete',views.order_complete,name='order_complete'),
]

Maria_Membership/models.py
from django.db import models
from django.conf import settings


# 가입 유저 모델
class Info(models.Model):
    # name = models.CharField(max_length=30)
    # birthDay = models.CharField(db_column='birthDay', max_length=8)
    # phoneNumber = models.CharField(db_column='phoneNumber', max_length=11, unique=True)
    uID = models.AutoField(primary_key=True)
    isOwner = models.BooleanField(default=False)
    uName = models.CharField(max_length=50)
    uPhone = models.CharField(max_length=11, unique=True)
    uBirthDay = models.CharField(max_length=8)
    uImage = models.CharField(max_length=1, default='')

    class Meta:
        db_table = 'USER'

# 메뉴 모델
class Menu(models.Model):
    user = models.ForeignKey(Info, on_delete=models.CASCADE)
    americano = models.IntegerField()
    latte = models.IntegerField()
    smoothy = models.IntegerField()
    total = models.IntegerField()

    class Meta:
        db_table = 'menu_info'


class Store(models.Model):
    sID = models.AutoField(primary_key=True)
    uID = models.ForeignKey(Info, on_delete=models.CASCADE, db_column="uID")
    sName = models.CharField(max_length=50)
    sPhone = models.CharField(max_length=50)
    class Meta:
        db_table = 'STORE'

class RMENU(models.Model):
    mID = models.AutoField(primary_key=True)
    sID  = models.ForeignKey(Store, on_delete=models.CASCADE, db_column="sID")
    mName = models.CharField(max_length=45)
    mDesc = models.CharField(max_length=45, null=True)
    mPrice = models.IntegerField()
    mImage = models.CharField(max_length=200)

    class Meta:
        db_table = 'MENU'

Maria_Membership/forms.py
from .models import Info, Menu
from django import forms


class InfoForm(forms.ModelForm):
    class Meta:
        model = Info
        fields = ('uName', 'uPhone', 'uBirthDay',)
        widgets = {
            'uBirthDay': forms.TextInput(attrs={'maxlength': 8, 'size': 20, 'placeholder': '예시: 19990101'}),
            'uPhone': forms.TextInput(attrs={'maxlength': 11, 'size': 20, 'placeholder': '예시: 01012349876'})
        }


class MenuForm(forms.ModelForm):
    class Meta:
        model = Menu
        fields = ('americano', 'latte', 'smoothy', 'total')
        widgets = {
            'americano': forms.TextInput(attrs={'size': 2, 'value': 0, 'id': 'id_americano', 'style': "border: none; background: transparent; text-align:right;", 'readonly': True, 'onclick': 'change1();'}),
            'latte': forms.TextInput(attrs={'size': 2, 'value': 0, 'id': 'id_latte', 'readonly': True, 'style': "border: none; background: transparent; text-align:right;", 'onclick': 'change2();'}),
            'smoothy': forms.TextInput(attrs={'size': 2, 'value': 0, 'id': 'id_smoothy', 'readonly': True, 'style': "border: none; background: transparent; text-align:right;", 'onclick': 'change3();'}),
            'total': forms.TextInput(attrs={'size': 3, 'value': 0, 'id': 'id_total', 'readonly': True, 'style': "border: none; background: transparent; text-align:right; padding-right:3px;"}),
        }

Maria_Membership/views.py
from django.shortcuts import render, redirect, get_object_or_404
from . import faceReconition, takePicture
from .models import Info, Menu, RMENU, Store
from .forms import InfoForm, MenuForm
# Create your views here.

userName = ''
userPhoneNumber = ''


def home(request):
    global userName, userPhoneNumber
    # store = Store.objects.get(sID=1)
    # print(store.sName)
    userName = ''
    userPhoneNumber = ''
    context = {
        'username':userName,
    }
    return render(request, 'home.html', context)

def information(request):
    form = InfoForm()
    context = {
        'form': form,
    }
    return render(request, 'form.html', context)


def reqfacePicture(request):
    global userName, userPhoneNumber
    if request.method == 'POST':
        form = InfoForm(request.POST)
        userName = request.POST['uName']
        userPhoneNumber = request.POST['uPhone']

        if form.is_valid():
            keyNumber = takePicture.takePt(userName, userPhoneNumber)

            # 스페이스 바를 누르면 저장을 진행
            if keyNumber == 32:
                user = form.save()
                return render(request, 'check.html')

            # ESC를 누를 경우 회원가입을 취소하고 회원정보 입력페이지로 돌아간다.
            elif keyNumber == 27:
                context = {
                    'form': form,
                }
                return render(request, 'cancel.html', context)

            # 사진이 제대로 찍히지 않은 경우
            elif keyNumber == 999:
                context = {
                    'form': form,
                }
                return render(request, 'noRecog.html', context)
        else:
            return render(request, 'return.html')

    # post방식이 아닌 주소를 쳐서 들어오면 홈으로 돌아간다.
    return redirect('Maria_membership:home')


def reqfaceRecog(request):
    global userPhoneNumber, userName

    if request.method == 'POST':
        try:
            userPhoneNumber = faceReconition.face()
        except:
            return redirect('Maria_membership:home')
        # 회원이 아닌 경우 홈화면으로 이동
        if userPhoneNumber == 'unknown':
            return redirect('Maria_membership:home')
        userinfo = get_object_or_404(Info, uPhone=userPhoneNumber)
        userName = userinfo.uName
        try:
            menuinfo = get_object_or_404(Menu, user=userinfo)
            menu_id = menuinfo.id
            menuinfo = get_object_or_404(Menu, user=userinfo, id=menu_id)
            americano = menuinfo.americano
            latte = menuinfo.latte
            smoothy = menuinfo.smoothy
            total = menuinfo.total
            favorite = [['아메리카노', americano, '3,000'], [
                '라떼', latte, '4,000'], ['스무디', smoothy, '5,000']]
            favorite = sorted(favorite, key=lambda x: x[1], reverse=True)
            context = {
                'userName': userName,
                'userPhoneNumber': userPhoneNumber,
                'first': favorite[0][1],
                'first_menu': favorite[0][0],
                'second': favorite[1][1],
                'second_menu': favorite[1][0],
                'third': favorite[2][1],
                'third_menu': favorite[2][0],
                'first_price': favorite[0][2],
                'second_price': favorite[1][2],
                'third_price': favorite[2][2],
                'total': total,
            }
        except:
            context = {
                'userName': userName,
                'userPhoneNumber': userPhoneNumber,
                'first': 0,
                'first_menu': '아메리카노',
                'second': 0,
                'second_menu': '라떼',
                'third': 0,
                'third_menu': '스무디',
                'first_price': '3,000',
                'second_price': '4,000',
                'third_price': '5,000',
                'total': 0,
            }
        return render(request, 'complete.html', context)

    return redirect('Maria_membership:home')

# 메인메뉴


def menu(request):
    global userPhoneNumber, userName
    menuForm = MenuForm()
    if request.method == 'POST':
        if userPhoneNumber != '':
            # 메뉴폼에 받은 정보 넣기
            form = MenuForm(request.POST)
            if form.is_valid():
                context = {
                    'form': form,
                }
                if request.POST.get('total') == '0':
                    return redirect('Maria_membership:menu')
                return render(request, 'order.html', context)
        else:
            context = {
                'username':userName,
                'form':menuForm,
            }
            return render(request,'menu.html',context)

    context = {
        'form': menuForm,
        'username': userName,
    }
    return render(request, 'menu.html', context)


def stamp(request):
    global userName, userPhoneNumber
    if request.method == "POST":
        userinfo = get_object_or_404(Info, uPhone=userPhoneNumber)
        try:

            menuinfo = get_object_or_404(Menu, user=userinfo)
            menu_id = menuinfo.id
            menuinfo = get_object_or_404(Menu, user=userinfo, id=menu_id)
            if menuinfo.total >= 10:
                menuinfo.total -= 10
                menuinfo.save()
            else:
                return redirect('Maria_membership:mypage')
        except:
            return redirect('Maria_membership:mypage')

        americano = menuinfo.americano
        latte = menuinfo.latte
        smoothy = menuinfo.smoothy
        total = menuinfo.total
        favorite = [['아메리카노', americano, '3,000'], [
            '라떼', latte, '4,000'], ['스무디', smoothy, '5,000']]
        favorite = sorted(favorite, key=lambda x: x[1], reverse=True)
        context = {
            'userName': userName,
            'userPhoneNumber': userPhoneNumber,
            'first': favorite[0][1],
            'first_menu': favorite[0][0],
            'second': favorite[1][1],
            'second_menu': favorite[1][0],
            'third': favorite[2][1],
            'third_menu': favorite[2][0],
            'first_price': favorite[0][2],
            'second_price': favorite[1][2],
            'third_price': favorite[2][2],
            'total': total,
        }
        return render(request, 'complete.html', context)

    return redirect('Maria_membership:home')


def mypage(request):
    global userPhoneNumber, userName
    if userPhoneNumber != '':
        try:
            userinfo = get_object_or_404(Info, uPhone=userPhoneNumber)
            menuinfo = get_object_or_404(Menu, user=userinfo)
            menu_id = menuinfo.id
            menuinfo = get_object_or_404(Menu, user=userinfo, id=menu_id)
            americano = menuinfo.americano
            latte = menuinfo.latte
            smoothy = menuinfo.smoothy
            total = menuinfo.total
            favorite = [['아메리카노', americano, '3,000'], [
                '라떼', latte, '4,000'], ['스무디', smoothy, '5,000']]
            favorite = sorted(favorite, key=lambda x: x[1], reverse=True)
            context = {
                'userName': userName,
                'userPhoneNumber': userPhoneNumber,
                'first': favorite[0][1],
                'first_menu': favorite[0][0],
                'second': favorite[1][1],
                'second_menu': favorite[1][0],
                'third': favorite[2][1],
                'third_menu': favorite[2][0],
                'first_price': favorite[0][2],
                'second_price': favorite[1][2],
                'third_price': favorite[2][2],
                'total': total,
            }
        except:
            context = {
                'userName': userName,
                'userPhoneNumber': userPhoneNumber,
                'first': 0,
                'first_menu': '아메리카노',
                'second': 0,
                'second_menu': '라떼',
                'third': 0,
                'third_menu': '스무디',
                'first_price': '3,000',
                'second_price': '4,000',
                'third_price': '5,000',
                'total': 0,
            }
        return render(request, 'complete.html', context)
    else:
        return redirect('Maria_membership:home')


def order_complete(request):
    global userName, userPhoneNumber
    if request.method == 'POST':
        form = MenuForm(request.POST)
        # 유니크한 폰번호로 db접근
        userinfo = get_object_or_404(Info, uPhone=userPhoneNumber)
        menu = form.save(commit=False)
        # 기존에 주문한 적이 있으면 try, 없으면 except문
        try:
            menuinfo = get_object_or_404(Menu, user=userinfo)
            menu_id = menuinfo.id
            menuinfo = get_object_or_404(Menu, user=userinfo, id=menu_id)
            menuinfo.americano += menu.americano
            menuinfo.latte += menu.latte
            menuinfo.smoothy += menu.smoothy
            menuinfo.total += menu.total
            menuinfo.save()

            context = {
                'form': menu,

            }
        except:
            menu.user = userinfo
            menu.save()
            context = {
                'form': form,

            }

        return redirect('Maria_membership:mypage')

    return redirect('Maria_membership:home')

Maria_Membership/templates/cancel.html
{% extends 'base.html' %}
{% block body %}
<form action="{% url 'Maria_membership:reqfacePicture' %}" method="POST">
  {% csrf_token %}
  <div class="info" style="width: 800px; height: 300px; margin-top:30px;">
    <table class="info_table">
      <tr style="height:80px;font-size: 36px;">
        <th style="width:300px;">이 름</th>
        <td>{{form.uName}}</td>
      </tr>
      <tr style="height:80px;font-size: 36px;">
        <th>생 년 월 일</th>
        <td>{{form.uBirthDay}}</td>
      </tr>
      <tr style="height:80px;font-size: 36px;">
        <th>전 화 번 호</th>
        <td>{{form.uPhone}}</td>
      </tr>
    </table>
    <button type='submit' class='btn btn-primary btn-lg btn-block' style="font-size: 36px; margin-top:50px;">RETRY A
      PICTURE</button>
    <h3 style="text-align:center;">촬영이 취소되었습니다.</h3>
  </div>
</form>

<style>
  .info {
    position: absolute;
    left: 50%;
    top: 50%;
    transform: translate(-50%, -50%)
  }
</style>
{% endblock %}

Maria_Membership/templates/home.html
{% extends 'base.html' %}
{% block body %}
{% load static %}
<div class="st">
  <img class="rounded mx-auto d-block" src="{% static 'img/main.jpg'%}" class="img-fluid" alt="Responsive image">
  <a href="{% url 'Maria_membership:information' %}"><button type="button"
      class="btn btn-info btn-lg btn-block">회원가입</button></a>
  <form action="{% url 'Maria_membership:reqfaceRecog' %}" method="POST">
    {% csrf_token %}
    <button type="submit" class="btn btn-warning btn-lg btn-block mt-3">얼굴인식 로그인</button>
  </form>
</div>
<style>
  .st {
    position: absolute;
    left: 50%;
    top: 50%;
    transform: translate(-50%, -50%)
  }
</style>
{% endblock %}

Maria_Membership/templates/menu.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>FACE-SHIP</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
    integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
  <link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700,800,900&display=swap"
    rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Jua&display=swap" rel="stylesheet">

  <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
  <!-- favicon -->
  <link rel="icon" href="{% static 'img/favicon_logo.png' %}">
</head>

<body onload="init();" style="font-family: 'Jua', sans-serif;">
  <!-- 네브바 -->
  <div style="font-family: 'Jua', sans-serif; font-size:40px;">
    <nav class="navbar navbar-dark bg-dark">
      <a class="navbar-brand" href="{% url 'Maria_membership:home' %}"><span
          style="color: dodgerblue; font-size:27px;">Face</span><span
          style="color: lightseagreen; font-size:27px;">Ship</span></a>
      <div>
        <a href="{% url 'Maria_membership:menu' %}" style=" color:white; margin-right:6px;">메뉴보기</a>
        {% if username == '' %}
        <a href="{% url 'Maria_membership:information' %}" style=" color:white;">회원가입</a>
        <form class="" action="{% url 'Maria_membership:reqfaceRecog' %}" method="POST"
          style="display:inline; cursor: pointer;text-align: right;">
          {% csrf_token %}
          <input class="login" type="submit" style="border: none; background: transparent; color: white;" value="로그인">
          <style>
            .login:hover {
              text-decoration: underline;
            }
          </style>
        </form>
        {% else %}
        <a href="{% url 'Maria_membership:mypage' %}" style="color:white;">내 정보</a>
        <a href="{% url 'Maria_membership:home' %}" style="color:white;">로그아웃</a>
        {% endif %}
      </div>
    </nav>
  </div>
  <div>
    <!-- Team -->
    <section id="team" class="pb-5" style="margin-top:50px;">
      <form class="menu-text" name="form1" method="POST" action="{% url 'Maria_membership:menu' %}">
        {% csrf_token %}
        <div style="margin: 5rem; font-size:35px;">
          <h5 class="section-title h1">메 뉴</h5>
          <br>
          <div class="row">
            <!-- Team member -->
            <div class="col-xs-12 col-sm-6 col-md-4">
              <div class="image-flip" ontouchstart="this.classList.toggle('hover');">
                <div class="mainflip">
                  <div class="frontside">
                    <div class="card">
                      <div class="card-body text-center">
                        <p><img class=" img-fluid" src="{% static 'img/ame.jpg' %}" style="width:200px;"
                            alt="card image">
                        </p>
                        <h4 class="card-title" style="font-size: 30px;">아메리카노</h4>
                        <span style="margin-right: 20px; margin-left: 2px;">
                          <span>수량</span>
                          <input type=hidden id="sell_price1" name="sell_price1" value="3000">
                          {{form.americano}}개
                          <span>금액</span>
                          <input class="money" type="text" name="sum1" size="6" readonly>원
                        </span>
                        <input type="button" class="btn btn-outline-primary btn-sm" value='+'
                          onclick="add1(); change4();">
                        <input type="button" class="btn btn-outline-primary btn-sm" value='-'
                          onclick="del1(); change4();">
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <!-- ./Team member -->
            <!-- Team member -->
            <div class="col-xs-12 col-sm-6 col-md-4">
              <div class="image-flip" ontouchstart="this.classList.toggle('hover');">
                <div class="mainflip">
                  <div class="frontside">
                    <div class="card">
                      <div class="card-body text-center">
                        <p><img class=" img-fluid" src="{% static 'img/latte.jpg' %}" style="width:200px;"
                            alt="card image"></p>
                        <h4 class="card-title" style="font-size:35px;">라떼</h4>
                        <!-- <p class="card-text">This is basic card with image on top, title, description and button.</p> -->
                        <span style="margin-right: 20px; margin-left: 2px;">
                          <span>수량</span> <input type=hidden name="sell_price2" value="4000">
                          {{form.latte}}개
                          <span>금액</span>
                          <input class="money" type="text" name="sum2" size="6" readonly>원
                        </span>

                        <input type="button" class="btn btn-outline-primary btn-sm" value='+'
                          onclick="add2(); change4();">
                        <input type="button" class="btn btn-outline-primary btn-sm" value='-'
                          onclick="del2(); change4();">
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <!-- ./Team member -->
            <!-- Team member -->
            <div class="col-xs-12 col-sm-6 col-md-4">
              <div class="image-flip" ontouchstart="this.classList.toggle('hover');">
                <div class="mainflip">
                  <div class="frontside">
                    <div class="card">
                      <div class="card-body text-center">
                        <p><img class=" img-fluid" src="{% static 'img/smoo.jfif' %}" style="width:255px;">
                        </p>
                        <h4 class="card-title" style="font-size:35px;">스무디</h4>
                        <!-- <p class="card-text">This is basic card with image on top, title, description and button.</p> -->
                        <span style="margin-right: 20px; margin-left: 2px;">
                          <span>수량</span>
                          <input type=hidden name="sell_price3" value="5000">
                          {{form.smoothy}}개
                          <span>금액</span>
                          <input class="money" type="text" name="sum3" size="6" readonly>원
                        </span>

                        <input type="button" class="btn btn-outline-primary btn-sm" value='+'
                          onclick="add3(); change4();">
                        <input type="button" class="btn btn-outline-primary btn-sm" value='-'
                          onclick="del3(); change4();">
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <!-- ./Team member -->
          </div>
        </div>
        <br>
        <div style="text-align:right; margin-right: 5rem; font-size: 40px;">
          <div style="display: none;">
            <span>총 수량 </span>
            {{form.total}}개
          </div>
          <span>총 금액 </span>
          <input class="money" type="text" name="sum4" size="6" readonly>원
          {% if username != "" %}
          <input type="submit" class="btn btn-outline-danger btn-lg" value='주문하기'>
          {% endif %}
        </div>
      </form>
    </section>
    <!-- JAVA Script -->
    <script language="JavaScript">
      var sell_price1;
      var sell_price2;
      var sell_price3;

      var americano;
      var latte;
      var smoothy;
      var total;

      var sum4;

      // 초기 실행
      function init() {
        sell_price1 = document.form1.sell_price1.value;
        americano = document.form1.americano.value;
        document.form1.sum1.value = sell_price1;
        change1();

        sell_price2 = document.form1.sell_price2.value;
        latte = document.form1.latte.value;
        document.form1.sum2.value = sell_price2;
        change2();

        sell_price3 = document.form1.sell_price3.value;
        smoothy = document.form1.smoothy.value;
        document.form1.sum3.value = sell_price3;
        change3();

        change4();

      }

      function add1() {
        hm1 = document.form1.americano;
        sum1 = document.form1.sum1;
        hm1.value++;
        sum1111 = document.form1.sum1111;
        sum_a = parseInt(hm1.value) * sell_price1;

        sum1.value = sum_a.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ",");

        sum4 = parseInt(sum1.value) + parseInt(sum2.value) + parseInt(sum3.value);
        document.getElementsByName('sum4').value = sum4
      }
      function add2() {
        hm2 = document.form1.latte;
        sum2 = document.form1.sum2;
        hm2.value++;
        sum_b = parseInt(hm2.value) * sell_price2;

        sum2.value = sum_b.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ",");

        sum4 = parseInt(sum1.value) + parseInt(sum2.value) + parseInt(sum3.value);
      }
      function add3() {
        hm3 = document.form1.smoothy;
        sum3 = document.form1.sum3;
        hm3.value++;
        sum_c = parseInt(hm3.value) * sell_price3;

        sum3.value = sum_c.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ",");

        sum4 = parseInt(sum1.value) + parseInt(sum2.value) + parseInt(sum3.value);
      }

      function del1() {
        hm1 = document.form1.americano;
        sum1 = document.form1.sum1;

        if (hm1.value > 0) {
          hm1.value--;
          aa = parseInt(hm1.value) * sell_price1;
          sum1.value = aa.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ",");

          sum4 = parseInt(sum1.value) + parseInt(sum2.value) + parseInt(sum3.value);
        }
      }
      function del2() {
        hm2 = document.form1.latte;
        sum2 = document.form1.sum2;
        if (hm2.value > 0) {
          hm2.value--;
          bb = parseInt(hm2.value) * sell_price2;
          sum2.value = bb.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ",");

          sum4 = parseInt(sum1.value) + parseInt(sum2.value) + parseInt(sum3.value);
        }
      }
      function del3() {
        hm3 = document.form1.smoothy;
        sum3 = document.form1.sum3;
        if (hm3.value > 0) {
          hm3.value--;
          cc = parseInt(hm3.value) * sell_price3;
          sum3.value = cc.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ",");

          sum4 = parseInt(sum1.value) + parseInt(sum2.value) + parseInt(sum3.value);
        }
      }

      function change1() {
        hm1 = document.form1.americano;
        sum1 = document.form1.sum1;
        sum1111 = document.form1.sum1111;

        if (hm1.value < 0) {
          hm1.value = 0;
        }
        sum1.value = parseInt(hm1.value) * sell_price1;


      }
      function change2() {
        hm2 = document.form1.latte;
        sum2 = document.form1.sum2;

        if (hm2.value < 0) {
          hm2.value = 0;
        }
        sum2.value = parseInt(hm2.value) * sell_price2;


      }
      function change3() {
        hm3 = document.form1.smoothy;
        sum3 = document.form1.sum3;

        if (hm3.value < 0) {
          hm3.value = 0;
        }
        sum3.value = parseInt(hm3.value) * sell_price3;

      }

      function change4() {
        hm1 = document.form1.americano;
        hm2 = document.form1.latte;
        hm3 = document.form1.smoothy;
        document.form1.total.value = parseInt(hm1.value) + parseInt(hm2.value) + parseInt(hm3.value)

        sum1 = document.form1.sum1;
        sum2 = document.form1.sum2;
        sum3 = document.form1.sum3;
        sum4 = document.form1.sum4;
        to = (parseInt(hm1.value) * sell_price1) + (parseInt(hm2.value) * sell_price2) + (parseInt(hm3.value) * sell_price3)
        sum4.value = to.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ",");
      }
    </script>
  </div>
  <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
    integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
    integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
    crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
    integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
    crossorigin="anonymous"></script>

</body>

</html>
<style>
  .menu-text_td>span {
    font-size: 20px;
  }

  .menu-text_td {
    width: 28%;
  }

  .out {
    width: 100%;
    text-align: center;
  }

  .in {
    display: inline-block;
  }

  .money {
    text-align: right;
    border: none;
    background: transparent;
  }
</style>

Maria_Membership/templates/nomember.html
{% extends 'base.html' %}
{% block body2 %}
<div class="st">
    <img class="rounded mx-auto d-block" src="https://newsimg.hankookilbo.com/2017/04/06/201704060483488399_1.jpg"
        class="img-fluid" alt="Responsive image">
    <h1 style="text-align:center;">회원이 아닙니다.</h1>
    <a href="{% url 'Maria_membership:information' %}"><button type="button"
            class="btn btn-info btn-lg btn-block">회원가입</button></a>
    <form action="{% url 'Maria_membership:reqfaceRecog' %}" method="POST">
        {% csrf_token %}
        <button type="submit" class="btn btn-warning btn-lg btn-block mt-3">얼굴인식 로그인</button>
    </form>
</div>
<style>
    .st {
        position: absolute;
        left: 50%;
        top: 50%;
        transform: translate(-50%, -50%)
    }
</style>
{% endblock %}